openapi: "3.0.0"
info:
  version: 1.0.0
  title: Cable Guy
  license:
    name: MIT
servers:
  - url: http://localhost:8033/v1.0
paths:
  /ethernet:
    get:
      summary: List of ethernet devices and the current configuration
      responses:
        '200':
          description: A list containing ethernet device information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DeviceConfiguration"

    post:
      summary: Configure a specific device
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeviceConfiguration"
      responses:
        '200':
          description: Null response

components:
  schemas:
    DeviceConfiguration:
      required:
        - name
        - configuration
      properties:
        name:
          type: string
          example: eth0
        info:
          properties:
            connected:
              type: boolean
              example: true
            number_of_disconnections:
              type: integer
              example: 1
        configuration:
          properties:
            ip:
              type: string
              example: "192.168.2.2"
              description: Can be 'undefined', default is '192.168.2.2'
            mode:
              type: string
              enum: ['client', 'server', 'unmanaged']
