name: Build and Deploy Raspberry Pi OS Image

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Deploy Images"]
    types:
      - completed

jobs:
  deploy-pi-img:
    if: ${{ ! github.event.issue.pull_request }}
    runs-on: self-hosted
    # The runner for this job is a Raspberry Pi OS Bullseye.
    # Just install docker (curl -sSL https://get.docker.com/ | sh) and follow the instructions for setting up a new runner in
    # https://github.com/bluerobotics/BlueOS-docker/settings/actions/runners/new

    strategy:
      matrix:
        platforms: ["linux/arm/v7"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Pimod Build
        # We use our own pimod as upstream doesn't provide armv7 images
        run: |
          VERSION=$GITHUB_REPOSITORY
          VERSION=${VERSION:-master}
          wget https://raw.githubusercontent.com/williangalvani/pimod/master/pimod.sh && chmod +x pimod.sh
          docker run --rm --privileged \
            -v $PWD:/files \
            -e PATH=/pimod:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
            -e GITHUB_REPOSITORY=$GITHUB_REPOSITORY \
            -e VERSION=$GITHUB_REF_NAME \
            --workdir=/files \
            --platform ${{ matrix.platforms }} williangalvani/pimod:latest pimod.sh deploy/pimod/blueos.Pifile

      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          # TODO: add GITHUB_REF_NAME after https://github.com/actions/upload-artifact/issues/231 is fixed
          # name: blueos-${{ env.GITHUB_REF_NAME }}.zip
          name: blueos.zip
          path: deploy/pimod/blueos.img
          if-no-files-found: error

      # This is required because docker has root permissions, which means the runner is unable to clear this cache normally
      - name: Cleanup
        if: ${{ always() }}
        run: sudo rm -rf .cache
