name: python-test

on: [push, pull_request]

jobs:
  python-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8] # Python 3.7 is the version in our buster image

    steps:
    -
      uses: actions/checkout@v2
    -
      name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    -
      name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel # wheel need to be installed before mavproxy
        pip install mavproxy
        pip install pyfakefs pytest-cov pytest-timeout pylint mypy isort black
        find . -type f -name "setup.py" | xargs --max-lines=1 --replace=% python % install --user
    -
      name: Run tests
      run: |
        ./.hooks/pre-push

    - uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: htmlcov